### ISSUE TITLE
packages.fluentbit.io DNS issues

### ISSUE THREAD

**Issue by jludvig** [fluent/fluent-bit-packaging#18]
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Helmut-Onna** [comment]
same here, https://packages.fluentbit.io/ = ERR_NAME_NOT_RESOLVED

**Comment by jludvig** [comment]
fyi: it's also being discussed over on their slack channel (fluent-bit via https://launchpass.com/fluent-all) perhaps updates or workarounds will arrive there

**Comment by jludvig** [comment]
Fixed
