### ISSUE TITLE
fluent-bit should use a more appropriate organizational signing key

### ISSUE THREAD

**Issue by justchris1** [fluent/fluent-bit-packaging#23]
It appears that fluent-bit is signed by someone's individual signing key:
```
Importing GPG key 0x6EA0722A:
 Userid     : "Eduardo Silva <eduardo@treasure-data.com>"
 Fingerprint: f209 d876 2a60 cd49 e680 633b 4ff8 368b 6ea0 722a
 From       : https://packages.fluentbit.io/fluentbit.key
```

This is different, for whatever reason, than TD's distribution of td-agent:
```
TreasureData                                                                                                 42 kB/s | 3.1 kB     00:00    
Importing GPG key 0xAB97ACBE:
 Userid     : "Treasure Data, Inc (Treasure Agent Official Signing key) <support@treasure-data.com>"
 Fingerprint: BEE6 8228 9B22 17F4 5AF4 CC3F 901F 9177 AB97 ACBE
 From       : https://packages.treasuredata.com/GPG-KEY-td-agent
```

It would be far better for the distribution to use an organizational key as opposed to an individual's key.  Ideally, it would use the same "Treasure Data" signing key for both, but it would be far better for them to at least be organizationally controlled.  If Eduardo leaves the organization, it would require changing of GPG key trust on all machines deploying fluent-bit which is highly undesirable.

**Comment by kenhys** [comment]
@edsiper how do you feel about this suggestion? It may be reasonable.

**Comment by edsiper** [comment]
thanks for raising this issue.

We are currently working on project governance and this makes totally sense. I will follow up with CNCF for best-practice and advice on how to manage this properly.

**Comment by justchris1** [comment]
It appears this may have been resolved?  In verifying issue 3618, it appears that the signing keys appear to be moved to releases@fluentbit.io.  

```
$ sudo yum install fluent-bit
Fluent Bit                                      2.5 kB/s | 866  B     00:00    
Fluent Bit                                       20 kB/s | 3.1 kB     00:00    
Importing GPG key 0x3888C1CD:
 Userid     : "Fluentbit releases (Releases signing key) <releases@fluentbit.io>"
 Fingerprint: C3C0 A285 34B9 293E AF51 FABD 9F9D DC08 3888 C1CD
 From       : https://packages.fluentbit.io/fluentbit.key
Is this ok [y/N]: 
```

I would close, but I am uncertain if this was a trial run or if it is now organizationally rolled out permanently as part of the release process.  If it is part of the process, please feel free to close.  Thanks for the added guard-rails!

**Comment by patrick-stephens** [comment]
Yeah it was changed deliberately.
