### ISSUE TITLE
Support for RHEL9

### ISSUE THREAD

**Issue by eeromakiesko** [fluent/fluent-bit-packaging#31]
There appears to be not yet packages for RHEL9. 
https://td-agent-package-browser.herokuapp.com/3/redhat/

Do you have schedule for RHEL9 addition?

**Comment by patrick-stephens** [comment]
This repo is no longer used, RHEL 9 is supported by Fluent Bit but `td-agent-bit` is no longer a package that is built: https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit
